name: Build and Test

on:  # Trigger: Here we can define, when this pipeline will be run automatically
  push:
    branches: [ "main" ]
    paths:
      - ./M008_BankAccount
      - ./M008_BankAccount_Tests
  workflow_dispatch:  # With this trigger, you can start the pipeline by hand (button)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
